export const BASE_URL = 'http://93.188.167.68:5700/api';
export const LOGIN_URL = '/clients/login';
export const FORGOTPASSWORD_URL = '/clients/forgotPasswordOtp';
export const RESETPASSWORD_URL = '/clients/resetPassword';
export const CHANGEPASSWORD_URL = '/clients/changePassword';
export const CONSOLIDATEACCOUNT_URL = '/accounts/consolidateAccount/';
export const CONSOLIDATEVALUATION_URL = '/accounts/consolidateValuation/';
export const ACCOUNTVALUATION_URL = '/accounts/accountValuation/';
export const CONSOLIDATEASSETS_URL = '/accounts/consolidateAssets?';
export const ACCOUNTASSETS_URL = '/accounts/accountAssets?';
export const CONSOLIDATEPERFORMANCE_URL = '/accounts/consolidatePerformance?';
export const ACCOUNTPERFORMANCE_URL = '/accounts/accountPerformance?';
export const ADDRESSLIST_URL = '/clients/addressList/';
export const ADDADDRESS_URL = '/clients/addAddress';
export const UPDATEADDRESS_URL = '/clients/updateAddress/';
export const DELETE_ADDRESS_URL = '/clients/deleteAddress/';
export const UPLOADIMAGE_URL = '/clients/imageUploader/'
// export const GET_USER_URL = "/users/getById/";
// export const UPDATE_USER_URL = "/users/update"
// export const REGISTER_USER_URL = "/users/register" 
